services:
  app:
    container_name: uptrader_app
    build: .
    expose:
      - 8000
    command: >
      sh -c ". .venv/bin/activate &&
             cd uptrader &&
             python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate --database=default &&
             gunicorn uptrader.wsgi:application --bind 0.0.0.0:8000"
    env_file: ".env"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres_network
      - nginx_network
    volumes:
      - static:/uptrader/uptrader/static

  postgres:
    container_name: uptrader_postgres
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres_network

  nginx:
    container_name: uptrader_nginx
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      app:
        condition: service_started
    restart: always
    networks:
      - nginx_network
    volumes:
      - static:/uptrader/uptrader/static

networks:
  postgres_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  static:
